package asc

//nolint:gochecknoinits // registry init is the idiomatic way to populate a type map
func init() {
	registerRows(feedbackRows)
	registerRows(crashesRows)
	registerRowsWithSingleResourceAdapter(reviewsRows)
	registerRows(customerReviewSummarizationsRows)
	registerRowsWithSingleResourceAdapter(appsRows)
	registerRows(appsWallRows)
	registerRowsWithSingleResourceAdapter(appClipsRows)
	registerRowsWithSingleToListAdapter[AppCategoryResponse, AppCategoriesResponse](appCategoriesRows)
	registerRowsWithSingleResourceAdapter(appInfosRows)
	registerRowsWithSingleResourceAdapter(appClipDefaultExperiencesRows)
	registerRowsWithSingleResourceAdapter(appClipDefaultExperienceLocalizationsRows)
	registerRows(appClipHeaderImageRows)
	registerRows(appClipAdvancedExperienceImageRows)
	registerRowsWithSingleResourceAdapter(appClipAdvancedExperiencesRows)
	registerRows(appSetupInfoResultRows)
	registerRowsWithSingleResourceAdapter(appTagsRows)
	registerRowsWithSingleResourceAdapter(marketplaceSearchDetailsRows)
	registerRowsWithSingleResourceAdapter(marketplaceWebhooksRows)
	registerRowsWithSingleResourceAdapter(webhooksRows)
	registerRowsWithSingleResourceAdapter(webhookDeliveriesRows)
	registerRowsWithSingleResourceAdapter(alternativeDistributionDomainsRows)
	registerRowsWithSingleResourceAdapter(alternativeDistributionKeysRows)
	registerRows(alternativeDistributionPackageRows)
	registerRowsWithSingleResourceAdapter(alternativeDistributionPackageVersionsRows)
	registerRowsWithSingleResourceAdapter(alternativeDistributionPackageVariantsRows)
	registerRowsWithSingleResourceAdapter(alternativeDistributionPackageDeltasRows)
	registerRowsWithSingleResourceAdapter(backgroundAssetsRows)
	registerRowsWithSingleResourceAdapter(backgroundAssetVersionsRows)
	registerIDStateRows(func(v *BackgroundAssetVersionAppStoreReleaseResponse) (string, string) {
		return v.Data.ID, v.Data.Attributes.State
	}, backgroundAssetVersionStateRows)
	registerIDStateRows(func(v *BackgroundAssetVersionExternalBetaReleaseResponse) (string, string) {
		return v.Data.ID, v.Data.Attributes.State
	}, backgroundAssetVersionStateRows)
	registerIDStateRows(func(v *BackgroundAssetVersionInternalBetaReleaseResponse) (string, string) {
		return v.Data.ID, v.Data.Attributes.State
	}, backgroundAssetVersionStateRows)
	registerRowsWithSingleResourceAdapter(backgroundAssetUploadFilesRows)
	registerRowsWithSingleResourceAdapter(nominationsRows)
	registerRows(linkagesRows)
	registerSingleLinkageRows(func(v *AppClipDefaultExperienceReviewDetailLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageResponse) ResourceData {
		return v.Data
	})
	registerSingleLinkageRows(func(v *AppClipDefaultExperienceLocalizationHeaderImageLinkageResponse) ResourceData {
		return v.Data
	})
	registerSingleLinkageRows(func(v *AppStoreVersionAgeRatingDeclarationLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppStoreVersionReviewDetailLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppStoreVersionAppClipDefaultExperienceLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppStoreVersionSubmissionLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppStoreVersionRoutingAppCoverageLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppStoreVersionAlternativeDistributionPackageLinkageResponse) ResourceData {
		return v.Data
	})
	registerSingleLinkageRows(func(v *AppStoreVersionGameCenterAppVersionLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *BuildAppLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *BuildAppStoreVersionLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *BuildBuildBetaDetailLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *BuildPreReleaseVersionLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *PreReleaseVersionAppLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoAgeRatingDeclarationLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoPrimaryCategoryLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoPrimarySubcategoryOneLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoPrimarySubcategoryTwoLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoSecondaryCategoryLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoSecondarySubcategoryOneLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoSecondarySubcategoryTwoLinkageResponse) ResourceData { return v.Data })
	registerRowsWithSingleResourceAdapter(bundleIDsRows)
	registerRowsWithSingleResourceAdapter(merchantIDsRows)
	registerRowsWithSingleResourceAdapter(passTypeIDsRows)
	registerRowsWithSingleResourceAdapter(certificatesRows)
	registerRowsWithSingleResourceAdapter(profilesRows)
	registerRowsWithSingleResourceAdapter(legacyInAppPurchasesRows)
	registerRowsWithSingleResourceAdapter(inAppPurchasesRows)
	registerRowsWithSingleResourceAdapter(inAppPurchaseLocalizationsRows)
	registerRowsWithSingleResourceAdapter(inAppPurchaseImagesRows)
	registerRows(inAppPurchasePricePointsRows)
	registerRowsErr(inAppPurchasePricesRows)
	registerRowsErr(inAppPurchaseOfferCodePricesRows)
	registerRowsWithSingleResourceAdapter(inAppPurchaseOfferCodesRows)
	registerRowsWithSingleResourceAdapter(inAppPurchaseOfferCodeCustomCodesRows)
	registerRowsWithSingleResourceAdapter(inAppPurchaseOfferCodeOneTimeUseCodesRows)
	registerRows(inAppPurchaseAvailabilityRows)
	registerRows(inAppPurchaseContentRows)
	registerRows(inAppPurchasePriceScheduleRows)
	registerRows(inAppPurchaseReviewScreenshotRows)
	registerRowsWithSingleResourceAdapter(appEventsRows)
	registerRowsWithSingleResourceAdapter(appEventLocalizationsRows)
	registerRowsWithSingleResourceAdapter(appEventScreenshotsRows)
	registerRowsWithSingleResourceAdapter(appEventVideoClipsRows)
	registerRowsWithSingleResourceAdapter(subscriptionGroupsRows)
	registerRowsWithSingleResourceAdapter(subscriptionsRows)
	registerRowsWithSingleResourceAdapter(promotedPurchasesRows)
	registerRowsErr(subscriptionPricesRows)
	registerRows(subscriptionPriceRows)
	registerRows(subscriptionAvailabilityRows)
	registerRows(subscriptionGracePeriodRows)
	registerRowsWithSingleResourceAdapter(territoriesRows)
	registerRowsErr(territoryAgeRatingsRows)
	registerRows(offerCodeValuesRows)
	registerRows(appPricePointsRows)
	registerRows(appPriceScheduleRows)
	registerRows(appPricesRows)
	registerRowsWithSingleResourceAdapter(buildsRows)
	registerRows(buildsCountRows)
	registerRows(buildBundlesRows)
	registerRows(buildBundleFileSizesRows)
	registerRowsWithSingleResourceAdapter(betaAppClipInvocationsRows)
	registerRowsWithSingleResourceAdapter(betaAppClipInvocationLocalizationsRows)
	registerRowsWithSingleToListAdapter[SubscriptionOfferCodeOneTimeUseCodeResponse, SubscriptionOfferCodeOneTimeUseCodesResponse](offerCodesRows)
	registerRowsWithSingleToListAdapter[SubscriptionOfferCodeCustomCodeResponse, SubscriptionOfferCodeCustomCodesResponse](offerCodeCustomCodesRows)
	registerRows(subscriptionOfferCodeRows)
	registerRowsWithSingleResourceAdapter(winBackOffersRows)
	registerRowsErr(winBackOfferPricesRows)
	registerRowsWithSingleResourceAdapter(appStoreVersionsRows)
	registerRowsWithSingleToListAdapter[PreReleaseVersionResponse, PreReleaseVersionsResponse](preReleaseVersionsRows)
	registerRows(buildIconsRows)
	registerRowsWithSingleResourceAdapter(buildUploadsRows)
	registerRows(buildsLatestNextRows)
	registerRowsWithSingleResourceAdapter(buildUploadFilesRows)
	registerDirect(func(v *AppClipDomainStatusResult, render func([]string, [][]string)) error {
		h, r := appClipDomainStatusMainRows(v)
		render(h, r)
		if len(v.Domains) > 0 {
			dh, dr := appClipDomainStatusDomainRows(v)
			render(dh, dr)
		}
		return nil
	})
	registerRows(winBackOfferDeleteResultRows)
	registerRows(subscriptionPriceDeleteResultRows)
	registerRowsErr(offerCodePricesRows)
	registerRows(appAvailabilityRows)
	registerRows(territoryAvailabilitiesRows)
	registerRows(endAppAvailabilityPreOrderRows)
	registerRowsWithSingleResourceAdapter(appStoreVersionLocalizationsRows)
	registerRowsWithSingleResourceAdapter(betaAppLocalizationsRows)
	registerRowsWithSingleResourceAdapter(betaBuildLocalizationsRows)
	registerRows(appInfoLocalizationsRows)
	registerRowsWithSingleResourceAdapter(appScreenshotSetsRows)
	registerRowsWithSingleResourceAdapter(appScreenshotsRows)
	registerRowsWithSingleResourceAdapter(appPreviewSetsRows)
	registerRowsWithSingleResourceAdapter(appPreviewsRows)
	registerRowsWithSingleResourceAdapter(betaGroupsRows)
	registerRowsWithSingleResourceAdapter(betaTestersRows)
	registerRowsWithSingleResourceAdapter(usersRows)
	registerRowsWithSingleResourceAdapter(actorsRows)
	registerRowsWithSingleResourceAdapter(devicesRows)
	registerRows(deviceLocalUDIDRows)
	registerRowsWithSingleResourceAdapter(userInvitationsRows)
	registerRows(userDeleteResultRows)
	registerRows(userInvitationRevokeResultRows)
	registerRowsWithSingleResourceAdapter(betaAppReviewDetailsRows)
	registerRowsWithSingleResourceAdapter(betaAppReviewSubmissionsRows)
	registerRowsWithSingleResourceAdapter(buildBetaDetailsRows)
	registerRowsWithSingleToListAdapter[BetaLicenseAgreementResponse, BetaLicenseAgreementsResponse](betaLicenseAgreementsRows)
	registerRows(buildBetaNotificationRows)
	registerRows(ageRatingDeclarationRows)
	registerRows(accessibilityDeclarationsRows)
	registerRows(accessibilityDeclarationRows)
	registerRows(appStoreReviewDetailRows)
	registerRows(appStoreReviewAttachmentsRows)
	registerRows(appStoreReviewAttachmentRows)
	registerRows(appClipAppStoreReviewDetailRows)
	registerRows(routingAppCoverageRows)
	registerRows(appEncryptionDeclarationsRows)
	registerRows(appEncryptionDeclarationRows)
	registerRows(appEncryptionDeclarationDocumentRows)
	registerRows(betaRecruitmentCriterionOptionsRows)
	registerRows(betaRecruitmentCriteriaRows)
	registerRows(betaRecruitmentCriteriaDeleteResultRows)
	registerResponseDataRows(betaGroupMetricsRows)
	registerRowsWithSingleResourceAdapter(sandboxTestersRows)
	registerRowsWithSingleResourceAdapter(bundleIDCapabilitiesRows)
	registerRows(localizationDownloadResultRows)
	registerRows(localizationUploadResultRows)
	registerRows(appInfoSetBatchResultRows)
	registerDirect(func(v *BuildUploadResult, render func([]string, [][]string)) error {
		h, r := buildUploadResultRows(v)
		render(h, r)
		if len(v.Operations) > 0 {
			oh, or := buildUploadOperationsRows(v.Operations)
			render(oh, or)
		}
		return nil
	})
	registerRows(buildExpireAllResultRows)
	registerRows(appScreenshotListResultRows)
	registerRows(screenshotSizesRows)
	registerRows(appPreviewListResultRows)
	registerDirect(func(v *AppScreenshotUploadResult, render func([]string, [][]string)) error {
		h, r := appScreenshotUploadResultMainRows(v)
		render(h, r)
		if len(v.Results) > 0 {
			ih, ir := assetUploadResultItemRows(v.Results)
			render(ih, ir)
		}
		return nil
	})
	registerDirect(func(v *AppPreviewUploadResult, render func([]string, [][]string)) error {
		h, r := appPreviewUploadResultMainRows(v)
		render(h, r)
		if len(v.Results) > 0 {
			ih, ir := assetUploadResultItemRows(v.Results)
			render(ih, ir)
		}
		return nil
	})
	registerDirect(func(v *CustomProductPageScreenshotUploadResult, render func([]string, [][]string)) error {
		h, r := customProductPageScreenshotUploadResultMainRows(v)
		render(h, r)
		if len(v.Results) > 0 {
			ih, ir := assetUploadResultItemRows(v.Results)
			render(ih, ir)
		}
		return nil
	})
	registerDirect(func(v *CustomProductPagePreviewUploadResult, render func([]string, [][]string)) error {
		h, r := customProductPagePreviewUploadResultMainRows(v)
		render(h, r)
		if len(v.Results) > 0 {
			ih, ir := assetUploadResultItemRows(v.Results)
			render(ih, ir)
		}
		return nil
	})
	registerRows(appClipAdvancedExperienceImageUploadResultRows)
	registerRows(appClipHeaderImageUploadResultRows)
	registerRows(assetDeleteResultRows)
	registerRows(appClipDefaultExperienceDeleteResultRows)
	registerRows(appClipDefaultExperienceLocalizationDeleteResultRows)
	registerRows(appClipAdvancedExperienceDeleteResultRows)
	registerRows(appClipAdvancedExperienceImageDeleteResultRows)
	registerRows(appClipHeaderImageDeleteResultRows)
	registerRows(betaAppClipInvocationDeleteResultRows)
	registerRows(betaAppClipInvocationLocalizationDeleteResultRows)
	registerRows(testFlightPublishResultRows)
	registerRows(appStorePublishResultRows)
	registerRows(salesReportResultRows)
	registerRows(financeReportResultRows)
	registerRows(financeRegionsRows)
	registerRows(analyticsReportRequestResultRows)
	registerRows(analyticsReportRequestDeleteResultRows)
	registerRowsWithSingleToListAdapter[AnalyticsReportRequestResponse, AnalyticsReportRequestsResponse](analyticsReportRequestsRows)
	registerRows(analyticsReportDownloadResultRows)
	registerRows(analyticsReportGetResultRows)
	registerRowsWithSingleToListAdapter[AnalyticsReportResponse, AnalyticsReportsResponse](analyticsReportsRows)
	registerRowsWithSingleToListAdapter[AnalyticsReportInstanceResponse, AnalyticsReportInstancesResponse](analyticsReportInstancesRows)
	registerRowsWithSingleToListAdapter[AnalyticsReportSegmentResponse, AnalyticsReportSegmentsResponse](analyticsReportSegmentsRows)
	registerRows(appStoreVersionSubmissionRows)
	registerRows(appStoreVersionSubmissionCreateRows)
	registerRows(appStoreVersionSubmissionStatusRows)
	registerRows(appStoreVersionSubmissionCancelRows)
	registerRows(appStoreVersionDetailRows)
	registerRows(appStoreVersionAttachBuildRows)
	registerRowsWithSingleToListAdapter[ReviewSubmissionResponse, ReviewSubmissionsResponse](reviewSubmissionsRows)
	registerRowsWithSingleToListAdapter[ReviewSubmissionItemResponse, ReviewSubmissionItemsResponse](reviewSubmissionItemsRows)
	registerRows(reviewSubmissionItemDeleteResultRows)
	registerRows(appStoreVersionReleaseRequestRows)
	registerRows(appStoreVersionPromotionCreateRows)
	registerRows(appStoreVersionPhasedReleaseRows)
	registerRows(appStoreVersionPhasedReleaseDeleteResultRows)
	registerRows(buildBetaGroupsUpdateRows)
	registerRows(buildIndividualTestersUpdateRows)
	registerRows(buildUploadDeleteResultRows)
	registerRows(inAppPurchaseDeleteResultRows)
	registerRows(appEventDeleteResultRows)
	registerRows(appEventLocalizationDeleteResultRows)
	registerRows(appEventSubmissionResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterAchievementsRows)
	registerRows(gameCenterAchievementDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterAchievementVersionsRows)
	registerRowsWithSingleResourceAdapter(gameCenterLeaderboardsRows)
	registerRows(gameCenterLeaderboardDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterLeaderboardVersionsRows)
	registerRowsWithSingleResourceAdapter(gameCenterLeaderboardSetsRows)
	registerRows(gameCenterLeaderboardSetDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterLeaderboardSetVersionsRows)
	registerRowsWithSingleResourceAdapter(gameCenterLeaderboardLocalizationsRows)
	registerRows(gameCenterLeaderboardLocalizationDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterLeaderboardReleasesRows)
	registerRows(gameCenterLeaderboardReleaseDeleteResultRows)
	registerRows(gameCenterLeaderboardEntrySubmissionRows)
	registerRows(gameCenterPlayerAchievementSubmissionRows)
	registerRowsWithSingleResourceAdapter(gameCenterLeaderboardSetReleasesRows)
	registerRows(gameCenterLeaderboardSetReleaseDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterLeaderboardSetLocalizationsRows)
	registerRows(gameCenterLeaderboardSetLocalizationDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterAchievementReleasesRows)
	registerRows(gameCenterAchievementReleaseDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterAchievementLocalizationsRows)
	registerRows(gameCenterAchievementLocalizationDeleteResultRows)
	registerRows(gameCenterLeaderboardImageUploadResultRows)
	registerRows(gameCenterLeaderboardImageDeleteResultRows)
	registerRows(gameCenterAchievementImageUploadResultRows)
	registerRows(gameCenterAchievementImageDeleteResultRows)
	registerRows(gameCenterLeaderboardSetImageUploadResultRows)
	registerRows(gameCenterLeaderboardSetImageDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterChallengesRows)
	registerRows(gameCenterChallengeDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterChallengeVersionsRows)
	registerRowsWithSingleResourceAdapter(gameCenterChallengeLocalizationsRows)
	registerRows(gameCenterChallengeLocalizationDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterChallengeImagesRows)
	registerRows(gameCenterChallengeImageUploadResultRows)
	registerRows(gameCenterChallengeImageDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterChallengeReleasesRows)
	registerRows(gameCenterChallengeReleaseDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterActivitiesRows)
	registerRows(gameCenterActivityDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterActivityVersionsRows)
	registerRowsWithSingleResourceAdapter(gameCenterActivityLocalizationsRows)
	registerRows(gameCenterActivityLocalizationDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterActivityImagesRows)
	registerRows(gameCenterActivityImageUploadResultRows)
	registerRows(gameCenterActivityImageDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterActivityReleasesRows)
	registerRows(gameCenterActivityReleaseDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterGroupsRows)
	registerRows(gameCenterGroupDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterAppVersionsRows)
	registerRows(gameCenterEnabledVersionsRows)
	registerRowsWithSingleResourceAdapter(gameCenterDetailsRows)
	registerRowsWithSingleResourceAdapter(gameCenterMatchmakingQueuesRows)
	registerRows(gameCenterMatchmakingQueueDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterMatchmakingRuleSetsRows)
	registerRows(gameCenterMatchmakingRuleSetDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterMatchmakingRulesRows)
	registerRows(gameCenterMatchmakingRuleDeleteResultRows)
	registerRowsWithSingleResourceAdapter(gameCenterMatchmakingTeamsRows)
	registerRows(gameCenterMatchmakingTeamDeleteResultRows)
	registerRows(gameCenterMetricsRows)
	registerRows(gameCenterMatchmakingRuleSetTestRows)
	registerRows(subscriptionGroupDeleteResultRows)
	registerRows(subscriptionDeleteResultRows)
	registerRows(betaTesterDeleteResultRows)
	registerRows(betaTesterGroupsUpdateResultRows)
	registerRows(betaTesterAppsUpdateResultRows)
	registerRows(betaTesterBuildsUpdateResultRows)
	registerRows(appBetaTestersUpdateResultRows)
	registerRows(betaFeedbackSubmissionDeleteResultRows)
	registerRows(appStoreVersionLocalizationDeleteResultRows)
	registerRows(betaAppLocalizationDeleteResultRows)
	registerRows(betaBuildLocalizationDeleteResultRows)
	registerRows(betaTesterInvitationResultRows)
	registerRows(promotedPurchaseDeleteResultRows)
	registerRows(appPromotedPurchasesLinkResultRows)
	registerRows(sandboxTesterClearHistoryResultRows)
	registerRows(bundleIDDeleteResultRows)
	registerRows(marketplaceSearchDetailDeleteResultRows)
	registerRows(marketplaceWebhookDeleteResultRows)
	registerRows(webhookDeleteResultRows)
	registerRows(webhookPingRows)
	registerRows(merchantIDDeleteResultRows)
	registerRows(passTypeIDDeleteResultRows)
	registerRows(bundleIDCapabilityDeleteResultRows)
	registerRows(certificateRevokeResultRows)
	registerRows(profileDeleteResultRows)
	registerRows(endUserLicenseAgreementRows)
	registerRows(endUserLicenseAgreementDeleteResultRows)
	registerRows(profileDownloadResultRows)
	registerRows(signingFetchResultRows)
	registerRows(xcodeCloudRunResultRows)
	registerRows(xcodeCloudStatusResultRows)
	registerRowsWithSingleToListAdapter[CiProductResponse, CiProductsResponse](ciProductsRows)
	registerRowsWithSingleToListAdapter[CiWorkflowResponse, CiWorkflowsResponse](ciWorkflowsRows)
	registerRowsWithSingleToListAdapter[ScmProviderResponse, ScmProvidersResponse](scmProvidersRows)
	registerRows(scmRepositoriesRows)
	registerRowsWithSingleToListAdapter[ScmGitReferenceResponse, ScmGitReferencesResponse](scmGitReferencesRows)
	registerRowsWithSingleToListAdapter[ScmPullRequestResponse, ScmPullRequestsResponse](scmPullRequestsRows)
	registerRowsWithSingleToListAdapter[CiBuildRunResponse, CiBuildRunsResponse](ciBuildRunsRows)
	registerRowsWithSingleToListAdapter[CiBuildActionResponse, CiBuildActionsResponse](ciBuildActionsRows)
	registerRowsWithSingleToListAdapter[CiMacOsVersionResponse, CiMacOsVersionsResponse](ciMacOsVersionsRows)
	registerRowsWithSingleToListAdapter[CiXcodeVersionResponse, CiXcodeVersionsResponse](ciXcodeVersionsRows)
	registerRowsWithSingleToListAdapter[CiArtifactResponse, CiArtifactsResponse](ciArtifactsRows)
	registerRowsWithSingleToListAdapter[CiTestResultResponse, CiTestResultsResponse](ciTestResultsRows)
	registerRowsWithSingleToListAdapter[CiIssueResponse, CiIssuesResponse](ciIssuesRows)
	registerRows(ciArtifactDownloadResultRows)
	registerRows(ciWorkflowDeleteResultRows)
	registerRows(ciProductDeleteResultRows)
	registerRows(customerReviewResponseRows)
	registerRows(customerReviewResponseDeleteResultRows)
	registerRows(accessibilityDeclarationDeleteResultRows)
	registerRows(appStoreReviewAttachmentDeleteResultRows)
	registerRows(routingAppCoverageDeleteResultRows)
	registerRows(nominationDeleteResultRows)
	registerRows(appEncryptionDeclarationBuildsUpdateResultRows)
	registerRowsWithSingleResourceAdapter(androidToIosAppMappingDetailsRows)
	registerRows(androidToIosAppMappingDeleteResultRows)
	registerIDBoolRows(func(v *AlternativeDistributionDomainDeleteResult) (string, bool) {
		return v.ID, v.Deleted
	}, alternativeDistributionDeleteResultRows)
	registerIDBoolRows(func(v *AlternativeDistributionKeyDeleteResult) (string, bool) {
		return v.ID, v.Deleted
	}, alternativeDistributionDeleteResultRows)
	registerRowsWithSingleResourceAdapter(appCustomProductPagesRows)
	registerRowsWithSingleResourceAdapter(appCustomProductPageVersionsRows)
	registerRowsWithSingleResourceAdapter(appCustomProductPageLocalizationsRows)
	registerRows(appKeywordsRows)
	registerRowsWithSingleResourceAdapter(appStoreVersionExperimentsRows)
	registerRowsWithSingleResourceAdapter(appStoreVersionExperimentsV2Rows)
	registerRowsWithSingleResourceAdapter(appStoreVersionExperimentTreatmentsRows)
	registerRowsWithSingleResourceAdapter(appStoreVersionExperimentTreatmentLocalizationsRows)
	registerRows(appCustomProductPageDeleteResultRows)
	registerRows(appCustomProductPageLocalizationDeleteResultRows)
	registerRows(appStoreVersionExperimentDeleteResultRows)
	registerRows(appStoreVersionExperimentTreatmentDeleteResultRows)
	registerRows(appStoreVersionExperimentTreatmentLocalizationDeleteResultRows)
	registerRowsErr(perfPowerMetricsRows)
	registerRows(diagnosticSignaturesRows)
	registerRowsErr(diagnosticLogsRows)
	registerRows(performanceDownloadResultRows)
	registerRows(notarySubmissionStatusRows)
	registerRows(notarySubmissionsListRows)
	registerRows(notarySubmissionLogsRows)
}
